//! Platform abstraction of Own Keyboard Switch.
//!
//! The engine talks to the operating system only through the traits defined
//! here. `okbs-platform-windows` and `okbs-platform-linux` implement them.
//! Everything is `Send`, so implementations can live on dedicated threads.

pub mod autoreplace_gate;
mod diagnostics;
mod error;
mod types;

pub use diagnostics::{DiagnosticItem, DiagnosticReport, DiagnosticStatus};
pub use error::PlatformError;
pub use types::{FocusEvent, InputEvent, InputTarget, KeyStroke, LayoutId, LayoutInfo, WindowInfo};

use crossbeam_channel::Sender;
use okbs_core::{KeyMap, PhysKey};
use std::path::Path;

/// Localized labels for the platform's autoreplace popup windows.
#[derive(Debug, Clone)]
pub struct AutoreplaceLabels {
    pub title: String,
    pub insert: String,
    pub close: String,
    pub empty: String,
    pub disabled: String,
    pub hint_help: String,
    pub menu_help: String,
    pub list_help: String,
}

/// An explicit choice from the insertion list. Do not log its text payload.
#[derive(Clone)]
pub struct AutoreplaceInsertion {
    pub item: okbs_core::config::AutoReplaceItem,
    pub target: Option<InputTarget>,
}

impl std::fmt::Debug for AutoreplaceInsertion {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.debug_struct("AutoreplaceInsertion")
            .field("target", &self.target)
            .finish_non_exhaustive()
    }
}

/// Non-activating hints and a floating insertion list. Owned by the UI thread.
pub trait AutoreplaceUi {
    fn configure(
        &mut self,
        settings: &okbs_core::config::AutoReplace,
        labels: AutoreplaceLabels,
        theme: okbs_core::config::Theme,
    ) -> Result<()>;
    fn hint(&mut self, index: Option<usize>) -> Result<()>;
    fn show_list(&mut self, toggle: bool, target: Option<InputTarget>) -> Result<()>;
    fn poll(&mut self) -> Option<AutoreplaceInsertion>;
}

/// Result type of platform operations.
pub type Result<T, E = PlatformError> = std::result::Result<T, E>;

/// Stops a background capture or subscription when dropped.
pub trait StopGuard: Send {
    /// Stops explicitly and waits for the background work to finish.
    fn stop(self: Box<Self>);
}

/// Global observer of keyboard (and mouse click) input.
pub trait KeyboardSource: Send {
    /// Starts capturing. Events are sent to `sink` until the guard is dropped.
    ///
    /// Implementations must not block the input path: they only translate raw
    /// events and send them. Events generated by [`Injector`] must be marked
    /// with `injected = true`.
    fn start(&mut self, sink: Sender<InputEvent>) -> Result<Box<dyn StopGuard>>;

    /// Whether Caps Lock is currently on, if the platform can tell.
    fn caps_lock_on(&self) -> Option<bool> {
        None
    }
}

/// Synthesizes keyboard input.
pub trait Injector: Send {
    /// Sends key strokes in order. Implementations mark them as injected.
    fn send(&mut self, strokes: &[KeyStroke]) -> Result<()>;

    /// Replays a source-specific unmapped key during an input transaction.
    fn send_unmapped(&mut self, _code: u32, _pressed: bool) -> Result<()> {
        Err(PlatformError::Unsupported("unmapped key injection"))
    }

    /// Types text directly as Unicode, bypassing the layout. Optional.
    fn type_unicode(&mut self, text: &str) -> Result<()> {
        let _ = text;
        Err(PlatformError::Unsupported("unicode text injection"))
    }

    /// Presses and releases `key`, holding `modifiers` around it.
    fn tap(&mut self, modifiers: &[PhysKey], key: PhysKey) -> Result<()> {
        let mut strokes = Vec::with_capacity(modifiers.len() * 2 + 2);
        strokes.extend(modifiers.iter().map(|&m| KeyStroke::press(m)));
        strokes.push(KeyStroke::press(key));
        strokes.push(KeyStroke::release(key));
        strokes.extend(modifiers.iter().rev().map(|&m| KeyStroke::release(m)));
        self.send(&strokes)
    }

    /// Presses `Backspace` `count` times.
    fn backspace(&mut self, count: usize) -> Result<()> {
        let strokes: Vec<KeyStroke> = (0..count)
            .flat_map(|_| {
                [
                    KeyStroke::press(PhysKey::Backspace),
                    KeyStroke::release(PhysKey::Backspace),
                ]
            })
            .collect();
        self.send(&strokes)
    }
}

/// Reads and changes the active keyboard layout.
pub trait LayoutManager: Send {
    /// Installed layouts in system order.
    fn layouts(&self) -> Result<Vec<LayoutInfo>>;

    /// Layout of the focused window (or the global layout where it is global).
    fn current(&self) -> Result<LayoutId>;

    /// Activates `layout` for the focused window.
    fn set(&mut self, layout: LayoutId) -> Result<()>;

    /// Characters produced by each key in `layout`.
    fn keymap(&self, layout: LayoutId) -> Result<KeyMap>;

    /// Reports layout changes made by the user or other programs.
    fn subscribe(&mut self, sink: Sender<LayoutId>) -> Result<Box<dyn StopGuard>> {
        let _ = sink;
        Err(PlatformError::Unsupported("layout change notifications"))
    }
}

/// Information about the focused window and control.
pub trait FocusInfo: Send {
    /// Stable identity used to avoid applying delayed input in another control.
    fn input_target(&self) -> Result<Option<InputTarget>> {
        Ok(None)
    }
    /// Restore a previously selected application for an explicit insertion.
    fn activate_target(&self, _target: InputTarget) -> Result<()> {
        Err(PlatformError::Unsupported("restore insertion target"))
    }
    /// The foreground window, if it can be determined on this desktop.
    fn active_window(&self) -> Result<Option<WindowInfo>>;

    /// Whether the focused control is a password field; `None` = unknown.
    fn is_password_field(&self) -> Result<Option<bool>>;

    /// Enter submits a command: completed lines cannot be erased or replayed.
    fn is_terminal(&self) -> Result<bool> {
        Ok(false)
    }

    /// Language of the underlined access keys in the menu bar of the focused
    /// window («Исправлять раскладку при работе с меню, содержащим горячие
    /// клавиши»). `None` when the window has no menu the platform can read.
    fn menu_access_language(&self) -> Result<Option<okbs_core::Lang>> {
        Ok(None)
    }

    /// Reports focus changes.
    fn subscribe(&mut self, sink: Sender<FocusEvent>) -> Result<Box<dyn StopGuard>> {
        let _ = sink;
        Err(PlatformError::Unsupported("focus change notifications"))
    }
}

/// Plain-text clipboard access.
pub trait Clipboard: Send {
    /// Current clipboard text, `None` if the clipboard holds no text.
    fn text(&mut self) -> Result<Option<String>>;

    /// Replaces the clipboard with `text`.
    fn set_text(&mut self, text: &str) -> Result<()>;

    /// Clears temporary text. Backends should override this to empty the clipboard.
    fn clear(&mut self) -> Result<()> {
        self.set_text("")
    }

    /// Reports clipboard changes.
    fn subscribe(&mut self, sink: Sender<()>) -> Result<Box<dyn StopGuard>> {
        let _ = sink;
        Err(PlatformError::Unsupported("clipboard change notifications"))
    }
}

/// Sound output.
pub trait SoundPlayer: Send {
    /// Plays WAV data asynchronously.
    fn play_wav(&self, data: &'static [u8]) -> Result<()>;

    /// Plays a WAV file asynchronously.
    fn play_file(&self, path: &Path) -> Result<()>;

    /// Short system beep.
    fn beep(&self) -> Result<()>;
}

/// Start-with-the-OS registration.
pub trait Autostart: Send {
    /// Whether the program is registered to start at login.
    fn is_enabled(&self) -> Result<bool>;

    /// Registers or unregisters `executable` to start at login.
    ///
    /// `elevated` asks for a registration that keeps administrator rights at
    /// login. Where the platform cannot do that, the ordinary registration is
    /// used and [`Autostart::elevated_at_login`] keeps reporting `false`.
    fn set_enabled(&self, enabled: bool, executable: &Path, elevated: bool) -> Result<()>;

    /// Whether the current registration starts the program with administrator
    /// rights.
    fn elevated_at_login(&self) -> Result<bool> {
        Ok(false)
    }
}

/// «Запускать с правами Администратора».
pub trait Elevation: Send {
    /// Whether this process has administrator rights.
    fn is_elevated(&self) -> bool;

    /// Starts `executable` with `arguments` again, asking the system for
    /// administrator rights. The caller exits once this succeeds.
    fn restart_elevated(&self, executable: &Path, arguments: &[String]) -> Result<()>;
}

/// Commands for the window the user is working in.
pub trait WindowControl: Send {
    /// Minimizes the foreground window.
    fn minimize_active(&self) -> Result<()>;

    /// Maximizes the foreground window, or restores it when it is maximized.
    fn toggle_maximize_active(&self) -> Result<()>;
}

/// What the floating layout indicator shows and how it behaves.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct IndicatorState {
    /// «Показывать плавающий индикатор».
    pub visible: bool,
    /// «Скрывать плавающий индикатор после смены раскладки».
    pub autohide: bool,
    /// How long it stays visible after a layout change when `autohide` is on.
    pub autohide_ms: u32,
    /// Saved position in physical screen pixels; `None` centres it at the top.
    pub position: Option<[i32; 2]>,
    /// «Закрепить индикатор»: the window cannot be dragged.
    pub locked: bool,
}

/// Localized entries of the indicator's context menu.
#[derive(Debug, Clone, Default)]
pub struct IndicatorLabels {
    pub title: String,
    pub lock: String,
    pub settings: String,
    pub hide: String,
}

/// What the user did with the indicator.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum IndicatorEvent {
    /// Dragged to a new position, in physical screen pixels.
    Moved([i32; 2]),
    /// «Закрепить индикатор» was switched.
    Locked(bool),
    /// «Скрыть индикатор» was chosen.
    Hidden,
    /// A double click asks for the settings window.
    OpenSettings,
}

/// A small always-on-top window with the current layout. It must never take
/// the input focus away from the program the user types in.
pub trait FloatingIndicator {
    /// Applies new settings and menu labels.
    fn configure(&mut self, state: &IndicatorState, labels: IndicatorLabels) -> Result<()>;

    /// Draws square `size` × `size` RGBA pixels. `layout_changed` restarts the
    /// auto-hide timer, showing the indicator again for a moment.
    fn set_icon(&mut self, rgba: &[u8], size: u32, layout_changed: bool) -> Result<()>;

    /// Next user action, if any.
    fn poll(&mut self) -> Option<IndicatorEvent>;
}

#[cfg(test)]
mod tests {
    use super::*;
    use std::sync::{Arc, Mutex};

    #[derive(Default)]
    struct Recorder(Arc<Mutex<Vec<KeyStroke>>>);

    impl Injector for Recorder {
        fn send(&mut self, strokes: &[KeyStroke]) -> Result<()> {
            self.0
                .lock()
                .map_err(|e| PlatformError::Other(e.to_string()))?
                .extend_from_slice(strokes);
            Ok(())
        }
    }

    #[test]
    fn tap_wraps_modifiers() {
        let log = Arc::new(Mutex::new(Vec::new()));
        let mut rec = Recorder(log.clone());
        rec.tap(&[PhysKey::ControlLeft, PhysKey::ShiftLeft], PhysKey::KeyV)
            .unwrap();
        assert_eq!(
            *log.lock().unwrap(),
            vec![
                KeyStroke::press(PhysKey::ControlLeft),
                KeyStroke::press(PhysKey::ShiftLeft),
                KeyStroke::press(PhysKey::KeyV),
                KeyStroke::release(PhysKey::KeyV),
                KeyStroke::release(PhysKey::ShiftLeft),
                KeyStroke::release(PhysKey::ControlLeft),
            ]
        );
    }

    #[test]
    fn backspace_repeats() {
        let log = Arc::new(Mutex::new(Vec::new()));
        let mut rec = Recorder(log.clone());
        rec.backspace(3).unwrap();
        assert_eq!(log.lock().unwrap().len(), 6);
        assert!(rec.type_unicode("x").is_err());
    }
}
