//! Data exchanged between platform backends and the engine.

use okbs_core::{Lang, PhysKey};
use std::path::PathBuf;
use std::time::Instant;

/// A raw input event.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub enum InputEvent {
    /// A physical key withheld by the source until the engine decides whether
    /// to consume it or replay it. Following keys are withheld in the same order.
    CapturedKey {
        epoch: u64,
        key: PhysKey,
        pressed: bool,
        repeat: bool,
        time: Instant,
        target: Option<InputTarget>,
    },
    /// An unmapped virtual key withheld while a replacement is in progress.
    CapturedUnknown {
        epoch: u64,
        code: u32,
        pressed: bool,
        time: Instant,
        target: Option<InputTarget>,
    },
    /// A key was pressed, auto-repeated or released.
    Key {
        /// Physical key.
        key: PhysKey,
        /// `true` for press and auto-repeat, `false` for release.
        pressed: bool,
        /// Auto-repeat of a held key.
        repeat: bool,
        /// Generated by this program's [`Injector`](crate::Injector).
        injected: bool,
        /// When the event was observed.
        time: Instant,
    },
    /// A key without a [`PhysKey`] mapping (media keys and similar).
    UnknownKey {
        /// Platform-specific code.
        code: u32,
        /// Press or release.
        pressed: bool,
        /// When the event was observed.
        time: Instant,
    },
    /// Any mouse button was pressed (the caret may have moved).
    MouseButton {
        /// When the event was observed.
        time: Instant,
        /// Owner of the clicked window, captured before Windows activates it.
        /// Never infer this from the foreground window later on the engine thread.
        in_own_window: bool,
    },
}

/// Identity of the foreground window and its focused control.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct InputTarget {
    pub window: u64,
    pub control: u64,
}

/// One synthetic key press or release.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash)]
pub struct KeyStroke {
    /// Key.
    pub key: PhysKey,
    /// Press (`true`) or release (`false`).
    pub pressed: bool,
}

impl KeyStroke {
    /// Key press.
    pub const fn press(key: PhysKey) -> Self {
        Self { key, pressed: true }
    }

    /// Key release.
    pub const fn release(key: PhysKey) -> Self {
        Self {
            key,
            pressed: false,
        }
    }
}

/// Platform-specific layout identifier: an `HKL` on Windows, a group index or
/// layout index on Linux.
#[derive(Debug, Clone, Copy, PartialEq, Eq, Hash, PartialOrd, Ord)]
pub struct LayoutId(pub u64);

/// An installed keyboard layout.
#[derive(Debug, Clone, PartialEq, Eq)]
pub struct LayoutInfo {
    /// Identifier for [`LayoutManager::set`](crate::LayoutManager::set).
    pub id: LayoutId,
    /// Detected language, if it is one the program supports.
    pub lang: Option<Lang>,
    /// BCP 47 locale such as `ru-RU` or `en-GB`; its region selects the flag.
    pub locale: String,
    /// Display name, e.g. `Русская` or `English (US)`.
    pub name: String,
    /// Short label for the tray, e.g. `Ru`.
    pub short: String,
}

/// The foreground window.
#[derive(Debug, Clone, Default, PartialEq, Eq)]
pub struct WindowInfo {
    /// Process id.
    pub pid: Option<u32>,
    /// Full path of the executable.
    pub executable: Option<PathBuf>,
    /// Window title.
    pub title: Option<String>,
    /// X11 `WM_CLASS`, Wayland `app_id`, or Windows window class.
    pub app_id: Option<String>,
}

/// Focus change notification.
#[derive(Debug, Clone, PartialEq, Eq)]
pub enum FocusEvent {
    /// Another window became active.
    WindowChanged(Option<WindowInfo>),
    /// The focused control inside the same window changed.
    ControlChanged,
    /// A menu bar the user opened with Alt was closed again.
    MenuClosed,
}
